configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
  #ip: 127.0.0.1
  port: 9740
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9740
moduleName: isp-lock-service

logfile:
  path: /var/log/isp-lock-service/runtime.log
  maxSizeMb: 512
  maxBackups: 4
  compress: true
